version: '3'

services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
    environment:
      NODE_ENV: production
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data