version: '3'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
